spring.application.name=reviewr2
spring.datasource.url=jdbc:postgresql://localhost:5432/reviewr2_db
spring.datasource.username=postgres
spring.datasource.password=postgre

# Keep Hibernate from auto-generating tables, Flyway will do this!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect