spring.application.name=reviewr2
spring.datasource.url=jdbc:postgresql://localhost:5432/reviewr2_db
spring.datasource.username=postgres
spring.datasource.password=postgre

# Keep Hibernate from auto-generating tables, Flyway will do this!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
# It looks for an OS environment variable named JWT_SECRET.
# If it doesn't find it, it uses the fallback string after the colon.
application.security.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=86400000